name: db_shelf
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  shelf_plus: ^1.10.0
  postgres: ^3.4.4

dev_dependencies:
  http: ^1.2.2
  lints: ^4.0.0
  test: ^1.24.0

dependency_overrides:
  postgres:
    git:
      url: https://github.com/davidmartos96/postgresql-dart.git
      ref: 150e1a1b6063521d1f38946b3bf4ff986a25f490